# Generated by Django 4.2.6 on 2023-10-30 13:48

from django.db import migrations, models

from myauth.models import avatar_images_directory_path


class Migration(migrations.Migration):

    dependencies = [
        ('myauth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(null=True, upload_to=avatar_images_directory_path),
        ),
    ]
